version: '3.7'

services:
  web:
    container_name: koru-jekyll-test
    image: koru-jekyll:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/project
    ports:
      - "4000:4000"